version: '3.7'

services:
  recipe-app-backend:
    build: .
    image: recipe-app-backend:latest
    container_name: recipe-app-backend
    ports:
        - 3001:3001
    environment:
      - RECIPE_SERVICE_PORT=3001
    restart: always
networks:
  default:
    name: recipe
